version: '3'
services:
  jupyter:
    build:
      context: .
      dockerfile: ./docker/jupyter/Dockerfile
    volumes:
      - ./ipynb:/home/jovyan/ipynb
      - ./data:/home/jovyan/data
    ports:
      - "8888:8888"
    env_file: 
      .env
    container_name: jupyter
  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    container_name: db
  luigi:
    build:
      context: ./docker/luigi
      dockerfile: Dockerfile
    volumes: 
      - ./data:/home/loader/data
    ports:
      - "8082:8082"
    container_name: luigi
volumes: 
  pgdata: